spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  # URL path version configuration
  mvc:
    apiversion:
      use:
        path-segment: 1
      supported: v1,v2    
      default: v1
      version-required: true  
    
logging:
  level:
    com.quiz.app: WARN
    org.springframework: WARN
    
management:
  endpoint:
    health:
      show-details: never
